[package]
name = "rustlib"
version = "0.1.0"
authors = ["halseth <johanth@gmail.com>"]

[lib]
name = "rustlib"
crate-type = ["staticlib"]

[dependencies]
bytes = "0.3.0"
multihash = "0.1.0"
rand = "0.3.14"
